[project]
name = "dota-autokey"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi",
    "httpx>=0.28.1",
    "keyboard",
    "pillow>=12.3.0",
    "pynput",
    "pyside6>=6.11.2",
    "pywin32>=312",
    "uvicorn[standard]",
    "bpy>=5.2",
    "numpy",
]

[tool.uv]
python-preference = "only-managed"
